const express = require('express');
const router = express.Router();

router.get('/', (req, res) => { 
    res.render('index',{title:'Movie Renting Application',message:'Movie Renting',newMessage:'Hi, This is generated by PugJS templating engine'}); 
});

module.exports = router;